#!/bin/bash
sudo apt remove -y goldendict
sudo apt remove -y gnome-robots
sudo apt remove -y gnome-chess
sudo apt remove -y aisleriot
sudo apt remove -y five-or-more
sudo apt remove -y gnome-mahjongg
sudo apt remove -y tali
sudo apt remove -y four-in-a-row
sudo apt remove -y gnome-klotski
sudo apt remove -y gnome-mines
sudo apt remove -y gnome-nibbles
sudo apt remove -y gnome-2048
sudo apt remove -y gnome-sudoku
sudo apt remove -y gnome-taquin
sudo apt remove -y gnome-tetravex
sudo apt remove -y hitori
sudo apt remove -y lightsoff
sudo apt remove -y quadrapassel
sudo apt remove -y swell-foop
sudo apt remove -y iagno
sudo apt remove -y anthy
sudo apt remove -y kasumi
killall -9 uim
sudo apt remove -y uim
sudo apt remove -y uim-data
sudo apt remove -y uim-mozc
sudo apt remove -y uim-xim
sudo apt remove -y im-config
sudo apt remove -y mozc-data
sudo apt remove -y mozc-utils-gui
sudo apt remove -y fcitx5-data
sudo apt remove -y fcitx-bin
sudo apt remove -y fcitx-module-dbus
sudo apt remove -y fcitx-config-common
sudo apt remove -y hunspell
sudo apt remove -y aspell
sudo apt remove -y eject
sudo apt remove -y vino
sudo apt remove -y xterm
sudo apt remove -y mlterm-common
sudo apt remove -y mlterm
sudo apt remove -y mlterm-tiny
sudo apt remove -y xiterm+thai
sudo apt remove -y malcontent
sudo apt autoremove
